name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: angela-mlh-portfolio
          heroku_email: wangela472@gmail.com

      - name: Test endpoints
        run: bash prod-test.sh

      - name: Send Discord notification upon unsuccessful deployment
        if: ${{ failure() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed"

      - name: Send Discord notification upon successful deployment
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚀 Deployment Successful !!"
